/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/erwang/.config/yarn/global/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-a531f4a8",
    path: "/code/frontend/304%E7%8A%B6%E6%80%81%E7%A0%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-a531f4a8").then(next)
    },
  },
  {
    path: "/code/frontend/304状态码.html",
    redirect: "/code/frontend/304%E7%8A%B6%E6%80%81%E7%A0%81.html"
  },
  {
    name: "v-1ca28292",
    path: "/code/frontend/CSS%E8%B8%A9%E5%9D%91%E5%B0%8F%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ca28292").then(next)
    },
  },
  {
    path: "/code/frontend/CSS踩坑小结.html",
    redirect: "/code/frontend/CSS%E8%B8%A9%E5%9D%91%E5%B0%8F%E7%BB%93.html"
  },
  {
    name: "v-57e956a7",
    path: "/code/frontend/ES6%E4%B8%AD%E7%B1%BB%E7%9A%84%E4%BD%BF%E7%94%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-57e956a7").then(next)
    },
  },
  {
    path: "/code/frontend/ES6中类的使用简明教程.html",
    redirect: "/code/frontend/ES6%E4%B8%AD%E7%B1%BB%E7%9A%84%E4%BD%BF%E7%94%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B.html"
  },
  {
    name: "v-06c9ecd1",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-06c9ecd1").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-4961d9e1",
    path: "/code/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4961d9e1").then(next)
    },
  },
  {
    path: "/code/index.html",
    redirect: "/code/"
  },
  {
    name: "v-7e89ae3c",
    path: "/code/frontend/JS%E4%B8%AD%E7%9B%91%E5%90%AC%E5%AF%B9%E8%B1%A1%E4%B8%AD%E5%8F%98%E9%87%8F%E7%9A%84%E5%8F%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e89ae3c").then(next)
    },
  },
  {
    path: "/code/frontend/JS中监听对象中变量的变化.html",
    redirect: "/code/frontend/JS%E4%B8%AD%E7%9B%91%E5%90%AC%E5%AF%B9%E8%B1%A1%E4%B8%AD%E5%8F%98%E9%87%8F%E7%9A%84%E5%8F%98%E5%8C%96.html"
  },
  {
    name: "v-0e335d95",
    path: "/code/frontend/JS%E4%B8%ADslice%E3%80%81substring%E3%80%81substr%E7%9A%84%E5%8C%BA%E5%88%AB.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0e335d95").then(next)
    },
  },
  {
    path: "/code/frontend/JS中slice、substring、substr的区别.html",
    redirect: "/code/frontend/JS%E4%B8%ADslice%E3%80%81substring%E3%80%81substr%E7%9A%84%E5%8C%BA%E5%88%AB.html"
  },
  {
    name: "v-439ae064",
    path: "/code/frontend/JS%E4%B8%ADapply%E3%80%81call%E3%80%81bind%E7%9A%84%E7%94%A8%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-439ae064").then(next)
    },
  },
  {
    path: "/code/frontend/JS中apply、call、bind的用法.html",
    redirect: "/code/frontend/JS%E4%B8%ADapply%E3%80%81call%E3%80%81bind%E7%9A%84%E7%94%A8%E6%B3%95.html"
  },
  {
    name: "v-41a7e09d",
    path: "/code/frontend/JS%E6%A3%80%E6%B5%8B%E7%BD%91%E7%BB%9C%E5%B8%A6%E5%AE%BD.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41a7e09d").then(next)
    },
  },
  {
    path: "/code/frontend/JS检测网络带宽.html",
    redirect: "/code/frontend/JS%E6%A3%80%E6%B5%8B%E7%BD%91%E7%BB%9C%E5%B8%A6%E5%AE%BD.html"
  },
  {
    name: "v-6995cf6a",
    path: "/code/frontend/Object.create.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6995cf6a").then(next)
    },
  },
  {
    name: "v-999a0f8a",
    path: "/code/frontend/JS%E6%9F%A5%E8%AF%A2URL%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%B8%AD%E7%9A%84%E5%8F%82%E6%95%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-999a0f8a").then(next)
    },
  },
  {
    path: "/code/frontend/JS查询URL字符串中的参数.html",
    redirect: "/code/frontend/JS%E6%9F%A5%E8%AF%A2URL%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%B8%AD%E7%9A%84%E5%8F%82%E6%95%B0.html"
  },
  {
    name: "v-526199ea",
    path: "/code/frontend/Object.defineProperty.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-526199ea").then(next)
    },
  },
  {
    name: "v-3f603604",
    path: "/code/frontend/Sass%E5%B0%8F%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3f603604").then(next)
    },
  },
  {
    path: "/code/frontend/Sass小结.html",
    redirect: "/code/frontend/Sass%E5%B0%8F%E7%BB%93.html"
  },
  {
    name: "v-242c6a39",
    path: "/code/frontend/JS%E8%8E%B7%E5%BE%97%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%90%84%E7%A7%8D%E9%AB%98%E5%BA%A6%E4%B8%8E%E5%AE%BD%E5%BA%A6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-242c6a39").then(next)
    },
  },
  {
    path: "/code/frontend/JS获得浏览器的各种高度与宽度.html",
    redirect: "/code/frontend/JS%E8%8E%B7%E5%BE%97%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%90%84%E7%A7%8D%E9%AB%98%E5%BA%A6%E4%B8%8E%E5%AE%BD%E5%BA%A6.html"
  },
  {
    name: "v-7bec828a",
    path: "/code/frontend/pushState%E4%B8%8EreplaceState.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7bec828a").then(next)
    },
  },
  {
    path: "/code/frontend/pushState与replaceState.html",
    redirect: "/code/frontend/pushState%E4%B8%8EreplaceState.html"
  },
  {
    name: "v-68b37bb8",
    path: "/code/frontend/%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-68b37bb8").then(next)
    },
  },
  {
    path: "/code/frontend/原型链.html",
    redirect: "/code/frontend/%E5%8E%9F%E5%9E%8B%E9%93%BE.html"
  },
  {
    name: "v-3de1df6c",
    path: "/code/git/%E5%B8%B8%E8%A7%81%E7%94%A8%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3de1df6c").then(next)
    },
  },
  {
    path: "/code/git/常见用法.html",
    redirect: "/code/git/%E5%B8%B8%E8%A7%81%E7%94%A8%E6%B3%95.html"
  },
  {
    name: "v-49f176ea",
    path: "/code/hot-key/Chrome.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-49f176ea").then(next)
    },
  },
  {
    name: "v-23019cbc",
    path: "/code/git/submodule.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-23019cbc").then(next)
    },
  },
  {
    name: "v-2f7a70dc",
    path: "/code/hot-key/Mac.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2f7a70dc").then(next)
    },
  },
  {
    name: "v-47bd24ec",
    path: "/code/hot-key/Vimium.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47bd24ec").then(next)
    },
  },
  {
    name: "v-542698b2",
    path: "/code/nginx/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E4%BC%98%E5%8C%96.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-542698b2").then(next)
    },
  },
  {
    path: "/code/nginx/通用配置优化.html",
    redirect: "/code/nginx/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E4%BC%98%E5%8C%96.html"
  },
  {
    name: "v-67f75cea",
    path: "/code/hot-key/VSCode.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-67f75cea").then(next)
    },
  },
  {
    name: "v-6f15f194",
    path: "/code/nginx/%E9%87%8D%E5%86%99%E8%B7%AF%E5%BE%84.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6f15f194").then(next)
    },
  },
  {
    path: "/code/nginx/重写路径.html",
    redirect: "/code/nginx/%E9%87%8D%E5%86%99%E8%B7%AF%E5%BE%84.html"
  },
  {
    name: "v-35a4dd01",
    path: "/read/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-35a4dd01").then(next)
    },
  },
  {
    path: "/read/index.html",
    redirect: "/read/"
  },
  {
    name: "v-1a1b5b16",
    path: "/read/%E5%8A%A8%E7%89%A9%E5%86%9C%E5%9C%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1a1b5b16").then(next)
    },
  },
  {
    path: "/read/动物农场.html",
    redirect: "/read/%E5%8A%A8%E7%89%A9%E5%86%9C%E5%9C%BA.html"
  },
  {
    name: "v-2c429899",
    path: "/read/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2c429899").then(next)
    },
  },
  {
    path: "/read/奥斯本检核表法.html",
    redirect: "/read/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html"
  },
  {
    name: "v-896a61a4",
    path: "/read/%E5%A4%A7%E6%95%99%E5%A0%82%E5%92%8C%E9%9B%86%E5%B8%82.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-896a61a4").then(next)
    },
  },
  {
    path: "/read/大教堂和集市.html",
    redirect: "/read/%E5%A4%A7%E6%95%99%E5%A0%82%E5%92%8C%E9%9B%86%E5%B8%82.html"
  },
  {
    name: "v-4d87729b",
    path: "/read/%E5%AF%92%E5%86%AC%E5%A4%9C%E8%A1%8C%E4%BA%BA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4d87729b").then(next)
    },
  },
  {
    path: "/read/寒冬夜行人.html",
    redirect: "/read/%E5%AF%92%E5%86%AC%E5%A4%9C%E8%A1%8C%E4%BA%BA.html"
  },
  {
    name: "v-78bb6638",
    path: "/read/%E7%A9%B7%E7%88%B8%E7%88%B8%E5%AF%8C%E7%88%B8%E7%88%B8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78bb6638").then(next)
    },
  },
  {
    path: "/read/穷爸爸富爸爸.html",
    redirect: "/read/%E7%A9%B7%E7%88%B8%E7%88%B8%E5%AF%8C%E7%88%B8%E7%88%B8.html"
  },
  {
    name: "v-1885256e",
    path: "/think/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1885256e").then(next)
    },
  },
  {
    path: "/think/奥斯本检核表法.html",
    redirect: "/think/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html"
  },
  {
    name: "v-474ce003",
    path: "/read/%E6%A0%91%E4%B8%8A%E7%9A%84%E7%94%B7%E7%88%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-474ce003").then(next)
    },
  },
  {
    path: "/read/树上的男爵.html",
    redirect: "/read/%E6%A0%91%E4%B8%8A%E7%9A%84%E7%94%B7%E7%88%B5.html"
  },
  {
    name: "v-22f72a52",
    path: "/read/%E9%86%89%E6%B1%89%E7%9A%84%E8%84%9A%E6%AD%A5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-22f72a52").then(next)
    },
  },
  {
    path: "/read/醉汉的脚步.html",
    redirect: "/read/%E9%86%89%E6%B1%89%E7%9A%84%E8%84%9A%E6%AD%A5.html"
  },
  {
    name: "v-30d11e4b",
    path: "/think/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30d11e4b").then(next)
    },
  },
  {
    path: "/think/index.html",
    redirect: "/think/"
  },
  {
    name: "v-19f300e1",
    path: "/view/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19f300e1").then(next)
    },
  },
  {
    path: "/view/index.html",
    redirect: "/view/"
  },
  {
    name: "v-01063b1e",
    path: "/code/frontend/JS%E4%B8%AD%E7%9A%84this.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01063b1e").then(next)
    },
  },
  {
    path: "/code/frontend/JS中的this.html",
    redirect: "/code/frontend/JS%E4%B8%AD%E7%9A%84this.html"
  },
  {
    name: "v-1238476e",
    path: "/view/%E9%BB%91%E9%95%9C%EF%BC%88%E7%AC%AC%E5%9B%9B%E5%AD%A3%EF%BC%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1238476e").then(next)
    },
  },
  {
    path: "/view/黑镜（第四季）.html",
    redirect: "/view/%E9%BB%91%E9%95%9C%EF%BC%88%E7%AC%AC%E5%9B%9B%E5%AD%A3%EF%BC%89.html"
  },
  {
    name: "v-4260720a",
    path: "/code/frontend/PWA.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4260720a").then(next)
    },
  },
  {
    name: "v-7a1161be",
    path: "/code/frontend/jsonp%E7%9A%84%E4%B8%80%E8%88%AC%E5%8E%9F%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7a1161be").then(next)
    },
  },
  {
    path: "/code/frontend/jsonp的一般原理.html",
    redirect: "/code/frontend/jsonp%E7%9A%84%E4%B8%80%E8%88%AC%E5%8E%9F%E7%90%86.html"
  },
  {
    name: "v-16a3280e",
    path: "/read/%E4%BA%BA%E6%83%85%E3%80%81%E9%9D%A2%E5%AD%90%E4%B8%8E%E6%9D%83%E5%88%A9%E7%9A%84%E5%86%8D%E7%94%9F%E4%BA%A7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-16a3280e").then(next)
    },
  },
  {
    path: "/read/人情、面子与权利的再生产.html",
    redirect: "/read/%E4%BA%BA%E6%83%85%E3%80%81%E9%9D%A2%E5%AD%90%E4%B8%8E%E6%9D%83%E5%88%A9%E7%9A%84%E5%86%8D%E7%94%9F%E4%BA%A7.html"
  },
  {
    name: "v-7f0cad55",
    path: "/read/%E5%A4%A7%E8%80%8C%E4%B8%8D%E5%80%92.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f0cad55").then(next)
    },
  },
  {
    path: "/read/大而不倒.html",
    redirect: "/read/%E5%A4%A7%E8%80%8C%E4%B8%8D%E5%80%92.html"
  },
  {
    name: "v-c591bb52",
    path: "/read/%E7%90%86%E8%A7%A3%E5%9B%BD%E9%99%85%E5%86%B2%E7%AA%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c591bb52").then(next)
    },
  },
  {
    path: "/read/理解国际冲突.html",
    redirect: "/read/%E7%90%86%E8%A7%A3%E5%9B%BD%E9%99%85%E5%86%B2%E7%AA%81.html"
  },
  {
    name: "v-7b2e433d",
    path: "/think/%E4%BF%A1%E6%81%AF%E8%BF%87%E5%89%A9%E4%B8%8E%E6%9E%81%E7%AE%80%E4%B8%BB%E4%B9%89.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7b2e433d").then(next)
    },
  },
  {
    path: "/think/信息过剩与极简主义.html",
    redirect: "/think/%E4%BF%A1%E6%81%AF%E8%BF%87%E5%89%A9%E4%B8%8E%E6%9E%81%E7%AE%80%E4%B8%BB%E4%B9%89.html"
  },
  {
    name: "v-19b77116",
    path: "/code/frontend/Typescript%E5%B0%8F%E7%BB%93.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-19b77116").then(next)
    },
  },
  {
    path: "/code/frontend/Typescript小结.html",
    redirect: "/code/frontend/Typescript%E5%B0%8F%E7%BB%93.html"
  },
  {
    name: "v-1175e57a",
    path: "/code/python/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1175e57a").then(next)
    },
  },
  {
    path: "/code/python/基础语法.html",
    redirect: "/code/python/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]