/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "王二的个人网站",
  "description": "记录生活，记录代码",
  "base": "/",
  "pages": [
    {
      "title": "304状态码",
      "frontmatter": {},
      "regularPath": "/code/frontend/304%E7%8A%B6%E6%80%81%E7%A0%81.html",
      "relativePath": "code/frontend/304状态码.md",
      "key": "v-a531f4a8",
      "path": "/code/frontend/304%E7%8A%B6%E6%80%81%E7%A0%81.html",
      "headers": [
        {
          "level": 3,
          "title": "一、详细讨论",
          "slug": "一、详细讨论"
        },
        {
          "level": 3,
          "title": "二、补充",
          "slug": "二、补充"
        }
      ]
    },
    {
      "title": "CSS踩坑小结",
      "frontmatter": {},
      "regularPath": "/code/frontend/CSS%E8%B8%A9%E5%9D%91%E5%B0%8F%E7%BB%93.html",
      "relativePath": "code/frontend/CSS踩坑小结.md",
      "key": "v-1ca28292",
      "path": "/code/frontend/CSS%E8%B8%A9%E5%9D%91%E5%B0%8F%E7%BB%93.html",
      "headers": [
        {
          "level": 3,
          "title": "一、iOS上的Safari没有滑动惯性",
          "slug": "一、ios上的safari没有滑动惯性"
        },
        {
          "level": 3,
          "title": "二、去除iphone中点击按钮会出现一个半透明的灰色背景的问题",
          "slug": "二、去除iphone中点击按钮会出现一个半透明的灰色背景的问题"
        },
        {
          "level": 3,
          "title": "三、div中保留文本的空格、换行以及tab字符的处理",
          "slug": "三、div中保留文本的空格、换行以及tab字符的处理"
        },
        {
          "level": 3,
          "title": "四、让盒子里的字超出长度后，可以缩略显示变成点点点",
          "slug": "四、让盒子里的字超出长度后，可以缩略显示变成点点点"
        },
        {
          "level": 3,
          "title": "五、word-wrap和word-break的区别",
          "slug": "五、word-wrap和word-break的区别"
        }
      ]
    },
    {
      "title": "ES6中类的使用简明教程",
      "frontmatter": {},
      "regularPath": "/code/frontend/ES6%E4%B8%AD%E7%B1%BB%E7%9A%84%E4%BD%BF%E7%94%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B.html",
      "relativePath": "code/frontend/ES6中类的使用简明教程.md",
      "key": "v-57e956a7",
      "path": "/code/frontend/ES6%E4%B8%AD%E7%B1%BB%E7%9A%84%E4%BD%BF%E7%94%A8%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B.html",
      "headers": [
        {
          "level": 3,
          "title": "一、开始",
          "slug": "一、开始"
        },
        {
          "level": 3,
          "title": "二、属性和方法",
          "slug": "二、属性和方法"
        },
        {
          "level": 3,
          "title": "三、constructor方法",
          "slug": "三、constructor方法"
        },
        {
          "level": 3,
          "title": "四、实例的属性",
          "slug": "四、实例的属性"
        },
        {
          "level": 3,
          "title": "五、不存在变量提升",
          "slug": "五、不存在变量提升"
        },
        {
          "level": 3,
          "title": "六、类的继承",
          "slug": "六、类的继承"
        },
        {
          "level": 3,
          "title": "七、存取器",
          "slug": "七、存取器"
        },
        {
          "level": 3,
          "title": "八、静态方法",
          "slug": "八、静态方法"
        },
        {
          "level": 3,
          "title": "九、实例属性",
          "slug": "九、实例属性"
        },
        {
          "level": 3,
          "title": "十、静态属性",
          "slug": "十、静态属性"
        }
      ]
    },
    {
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-06c9ecd1",
      "path": "/",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "代码记录",
      "frontmatter": {},
      "regularPath": "/code/",
      "relativePath": "code/README.md",
      "key": "v-4961d9e1",
      "path": "/code/",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "JS中监听对象中变量的变化",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E4%B8%AD%E7%9B%91%E5%90%AC%E5%AF%B9%E8%B1%A1%E4%B8%AD%E5%8F%98%E9%87%8F%E7%9A%84%E5%8F%98%E5%8C%96.html",
      "relativePath": "code/frontend/JS中监听对象中变量的变化.md",
      "key": "v-7e89ae3c",
      "path": "/code/frontend/JS%E4%B8%AD%E7%9B%91%E5%90%AC%E5%AF%B9%E8%B1%A1%E4%B8%AD%E5%8F%98%E9%87%8F%E7%9A%84%E5%8F%98%E5%8C%96.html",
      "headers": [
        {
          "level": 3,
          "title": "一、利用 Proxy 实现监听 js 中变量的变化",
          "slug": "一、利用-proxy-实现监听-js-中变量的变化"
        },
        {
          "level": 3,
          "title": "二、用 Object.defineProperty 实现监听 js 中变量的变化",
          "slug": "二、用-object-defineproperty-实现监听-js-中变量的变化"
        }
      ]
    },
    {
      "title": "JS中slice、substring、substr的区别",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E4%B8%ADslice%E3%80%81substring%E3%80%81substr%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "relativePath": "code/frontend/JS中slice、substring、substr的区别.md",
      "key": "v-0e335d95",
      "path": "/code/frontend/JS%E4%B8%ADslice%E3%80%81substring%E3%80%81substr%E7%9A%84%E5%8C%BA%E5%88%AB.html",
      "headers": [
        {
          "level": 3,
          "title": "一、substring()",
          "slug": "一、substring"
        },
        {
          "level": 3,
          "title": "二、substr()",
          "slug": "二、substr"
        },
        {
          "level": 3,
          "title": "三、substring()与substr()的主要区别",
          "slug": "三、substring-与substr-的主要区别"
        },
        {
          "level": 3,
          "title": "四、slice()",
          "slug": "四、slice"
        }
      ]
    },
    {
      "title": "JS中apply、call、bind的用法",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E4%B8%ADapply%E3%80%81call%E3%80%81bind%E7%9A%84%E7%94%A8%E6%B3%95.html",
      "relativePath": "code/frontend/JS中apply、call、bind的用法.md",
      "key": "v-439ae064",
      "path": "/code/frontend/JS%E4%B8%ADapply%E3%80%81call%E3%80%81bind%E7%9A%84%E7%94%A8%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "一、了解apply()的作用",
          "slug": "一、了解apply-的作用"
        },
        {
          "level": 3,
          "title": "二、apply()与call()的区别",
          "slug": "二、apply-与call-的区别"
        },
        {
          "level": 3,
          "title": "三、bind()是干什么用的",
          "slug": "三、bind-是干什么用的"
        },
        {
          "level": 3,
          "title": "四、总结",
          "slug": "四、总结"
        }
      ]
    },
    {
      "title": "JS检测网络带宽",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E6%A3%80%E6%B5%8B%E7%BD%91%E7%BB%9C%E5%B8%A6%E5%AE%BD.html",
      "relativePath": "code/frontend/JS检测网络带宽.md",
      "key": "v-41a7e09d",
      "path": "/code/frontend/JS%E6%A3%80%E6%B5%8B%E7%BD%91%E7%BB%9C%E5%B8%A6%E5%AE%BD.html",
      "headers": [
        {
          "level": 3,
          "title": "1、方法一",
          "slug": "_1、方法一"
        },
        {
          "level": 3,
          "title": "2、方法二",
          "slug": "_2、方法二"
        },
        {
          "level": 3,
          "title": "3、方法三",
          "slug": "_3、方法三"
        }
      ]
    },
    {
      "title": "Object.create",
      "frontmatter": {},
      "regularPath": "/code/frontend/Object.create.html",
      "relativePath": "code/frontend/Object.create.md",
      "key": "v-6995cf6a",
      "path": "/code/frontend/Object.create.html"
    },
    {
      "title": "JS查询URL字符串中的参数",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E6%9F%A5%E8%AF%A2URL%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%B8%AD%E7%9A%84%E5%8F%82%E6%95%B0.html",
      "relativePath": "code/frontend/JS查询URL字符串中的参数.md",
      "key": "v-999a0f8a",
      "path": "/code/frontend/JS%E6%9F%A5%E8%AF%A2URL%E5%AD%97%E7%AC%A6%E4%B8%B2%E4%B8%AD%E7%9A%84%E5%8F%82%E6%95%B0.html"
    },
    {
      "title": "JS中Object.defineProperty的使用方法",
      "frontmatter": {},
      "regularPath": "/code/frontend/Object.defineProperty.html",
      "relativePath": "code/frontend/Object.defineProperty.md",
      "key": "v-526199ea",
      "path": "/code/frontend/Object.defineProperty.html"
    },
    {
      "title": "Sass小结",
      "frontmatter": {},
      "regularPath": "/code/frontend/Sass%E5%B0%8F%E7%BB%93.html",
      "relativePath": "code/frontend/Sass小结.md",
      "key": "v-3f603604",
      "path": "/code/frontend/Sass%E5%B0%8F%E7%BB%93.html",
      "headers": [
        {
          "level": 3,
          "title": "一、SCSS 与 Sass 异同",
          "slug": "一、scss-与-sass-异同"
        },
        {
          "level": 3,
          "title": "二、 变量名用中划线还是下划线？",
          "slug": "二、-变量名用中划线还是下划线？"
        },
        {
          "level": 3,
          "title": "三、子组合选择器和同层组合选择器：>、+和~",
          "slug": "三、子组合选择器和同层组合选择器：-、-和"
        },
        {
          "level": 3,
          "title": "四、静默注释",
          "slug": "四、静默注释"
        },
        {
          "level": 3,
          "title": "五、混合器",
          "slug": "五、混合器"
        }
      ]
    },
    {
      "title": "JS获得浏览器的各种高度与宽度",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E8%8E%B7%E5%BE%97%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%90%84%E7%A7%8D%E9%AB%98%E5%BA%A6%E4%B8%8E%E5%AE%BD%E5%BA%A6.html",
      "relativePath": "code/frontend/JS获得浏览器的各种高度与宽度.md",
      "key": "v-242c6a39",
      "path": "/code/frontend/JS%E8%8E%B7%E5%BE%97%E6%B5%8F%E8%A7%88%E5%99%A8%E7%9A%84%E5%90%84%E7%A7%8D%E9%AB%98%E5%BA%A6%E4%B8%8E%E5%AE%BD%E5%BA%A6.html"
    },
    {
      "title": "pushState与replaceState",
      "frontmatter": {},
      "regularPath": "/code/frontend/pushState%E4%B8%8EreplaceState.html",
      "relativePath": "code/frontend/pushState与replaceState.md",
      "key": "v-7bec828a",
      "path": "/code/frontend/pushState%E4%B8%8EreplaceState.html",
      "headers": [
        {
          "level": 3,
          "title": "一、简介",
          "slug": "一、简介"
        },
        {
          "level": 3,
          "title": "二、pushState() 方法的例子",
          "slug": "二、pushstate-方法的例子"
        },
        {
          "level": 3,
          "title": "三、pushState() 方法",
          "slug": "三、pushstate-方法"
        },
        {
          "level": 3,
          "title": "四、pushState() 方法与设置hash值的区别",
          "slug": "四、pushstate-方法与设置hash值的区别"
        },
        {
          "level": 3,
          "title": "五、replaceState() 方法",
          "slug": "五、replacestate-方法"
        },
        {
          "level": 3,
          "title": "六、popstate 事件",
          "slug": "六、popstate-事件"
        },
        {
          "level": 3,
          "title": "七、popstate 事件的例子",
          "slug": "七、popstate-事件的例子"
        },
        {
          "level": 3,
          "title": "八、pushState()的用途",
          "slug": "八、pushstate-的用途"
        },
        {
          "level": 3,
          "title": "九、参考文章",
          "slug": "九、参考文章"
        }
      ]
    },
    {
      "title": "原型链",
      "frontmatter": {},
      "regularPath": "/code/frontend/%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
      "relativePath": "code/frontend/原型链.md",
      "key": "v-68b37bb8",
      "path": "/code/frontend/%E5%8E%9F%E5%9E%8B%E9%93%BE.html",
      "headers": [
        {
          "level": 3,
          "title": "一、认识原型",
          "slug": "一、认识原型"
        },
        {
          "level": 3,
          "title": "二、认识原型链",
          "slug": "二、认识原型链"
        },
        {
          "level": 3,
          "title": "三、原型链的继承",
          "slug": "三、原型链的继承"
        },
        {
          "level": 3,
          "title": "三、用以上原型链继承带来的问题",
          "slug": "三、用以上原型链继承带来的问题"
        },
        {
          "level": 3,
          "title": "四、ES6的新关键字class",
          "slug": "四、es6的新关键字class"
        }
      ]
    },
    {
      "title": "常见用法",
      "frontmatter": {},
      "regularPath": "/code/git/%E5%B8%B8%E8%A7%81%E7%94%A8%E6%B3%95.html",
      "relativePath": "code/git/常见用法.md",
      "key": "v-3de1df6c",
      "path": "/code/git/%E5%B8%B8%E8%A7%81%E7%94%A8%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "有意思的用法",
          "slug": "有意思的用法"
        },
        {
          "level": 3,
          "title": "常见快捷方式",
          "slug": "常见快捷方式"
        }
      ],
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "Chrome常用的快捷键",
      "frontmatter": {},
      "regularPath": "/code/hot-key/Chrome.html",
      "relativePath": "code/hot-key/Chrome.md",
      "key": "v-49f176ea",
      "path": "/code/hot-key/Chrome.html"
    },
    {
      "title": "git submodule 一般用法",
      "frontmatter": {},
      "regularPath": "/code/git/submodule.html",
      "relativePath": "code/git/submodule.md",
      "key": "v-23019cbc",
      "path": "/code/git/submodule.html",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "Mac常用的快捷键",
      "frontmatter": {},
      "regularPath": "/code/hot-key/Mac.html",
      "relativePath": "code/hot-key/Mac.md",
      "key": "v-2f7a70dc",
      "path": "/code/hot-key/Mac.html"
    },
    {
      "title": "Vimium常用的快捷键",
      "frontmatter": {},
      "regularPath": "/code/hot-key/Vimium.html",
      "relativePath": "code/hot-key/Vimium.md",
      "key": "v-47bd24ec",
      "path": "/code/hot-key/Vimium.html",
      "headers": [
        {
          "level": 3,
          "title": "Vimium的常用快捷键",
          "slug": "vimium的常用快捷键"
        }
      ]
    },
    {
      "title": "nginx 通用配置优化",
      "frontmatter": {},
      "regularPath": "/code/nginx/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E4%BC%98%E5%8C%96.html",
      "relativePath": "code/nginx/通用配置优化.md",
      "key": "v-542698b2",
      "path": "/code/nginx/%E9%80%9A%E7%94%A8%E9%85%8D%E7%BD%AE%E4%BC%98%E5%8C%96.html",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "VSCode常用的快捷键",
      "frontmatter": {},
      "regularPath": "/code/hot-key/VSCode.html",
      "relativePath": "code/hot-key/VSCode.md",
      "key": "v-67f75cea",
      "path": "/code/hot-key/VSCode.html"
    },
    {
      "title": "nginx 重写路径",
      "frontmatter": {},
      "regularPath": "/code/nginx/%E9%87%8D%E5%86%99%E8%B7%AF%E5%BE%84.html",
      "relativePath": "code/nginx/重写路径.md",
      "key": "v-6f15f194",
      "path": "/code/nginx/%E9%87%8D%E5%86%99%E8%B7%AF%E5%BE%84.html",
      "headers": [
        {
          "level": 3,
          "title": "可以使用 rewrite",
          "slug": "可以使用-rewrite"
        },
        {
          "level": 3,
          "title": "也可以用 alias",
          "slug": "也可以用-alias"
        }
      ],
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "阅读",
      "frontmatter": {},
      "regularPath": "/read/",
      "relativePath": "read/README.md",
      "key": "v-35a4dd01",
      "path": "/read/",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "动物农场",
      "frontmatter": {},
      "regularPath": "/read/%E5%8A%A8%E7%89%A9%E5%86%9C%E5%9C%BA.html",
      "relativePath": "read/动物农场.md",
      "key": "v-1a1b5b16",
      "path": "/read/%E5%8A%A8%E7%89%A9%E5%86%9C%E5%9C%BA.html",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "奥斯本检核表法",
      "frontmatter": {},
      "regularPath": "/read/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
      "relativePath": "read/奥斯本检核表法.md",
      "key": "v-2c429899",
      "path": "/read/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "一、能否他用",
          "slug": "一、能否他用"
        },
        {
          "level": 3,
          "title": "二、能否借用",
          "slug": "二、能否借用"
        },
        {
          "level": 3,
          "title": "三、能否改变",
          "slug": "三、能否改变"
        },
        {
          "level": 3,
          "title": "四、能否扩大",
          "slug": "四、能否扩大"
        },
        {
          "level": 3,
          "title": "八、能否颠倒",
          "slug": "八、能否颠倒"
        },
        {
          "level": 3,
          "title": "九、能否组合",
          "slug": "九、能否组合"
        }
      ],
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "大教堂和集市",
      "frontmatter": {},
      "regularPath": "/read/%E5%A4%A7%E6%95%99%E5%A0%82%E5%92%8C%E9%9B%86%E5%B8%82.html",
      "relativePath": "read/大教堂和集市.md",
      "key": "v-896a61a4",
      "path": "/read/%E5%A4%A7%E6%95%99%E5%A0%82%E5%92%8C%E9%9B%86%E5%B8%82.html",
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "寒冬夜行人",
      "frontmatter": {},
      "regularPath": "/read/%E5%AF%92%E5%86%AC%E5%A4%9C%E8%A1%8C%E4%BA%BA.html",
      "relativePath": "read/寒冬夜行人.md",
      "key": "v-4d87729b",
      "path": "/read/%E5%AF%92%E5%86%AC%E5%A4%9C%E8%A1%8C%E4%BA%BA.html"
    },
    {
      "title": "穷爸爸富爸爸",
      "frontmatter": {},
      "regularPath": "/read/%E7%A9%B7%E7%88%B8%E7%88%B8%E5%AF%8C%E7%88%B8%E7%88%B8.html",
      "relativePath": "read/穷爸爸富爸爸.md",
      "key": "v-78bb6638",
      "path": "/read/%E7%A9%B7%E7%88%B8%E7%88%B8%E5%AF%8C%E7%88%B8%E7%88%B8.html",
      "headers": [
        {
          "level": 3,
          "title": "一、现金流游戏",
          "slug": "一、现金流游戏"
        },
        {
          "level": 3,
          "title": "二、摘录",
          "slug": "二、摘录"
        },
        {
          "level": 3,
          "title": "三、给王二的启示",
          "slug": "三、给王二的启示"
        }
      ]
    },
    {
      "title": "奥斯本检核表法",
      "frontmatter": {},
      "regularPath": "/think/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
      "relativePath": "think/奥斯本检核表法.md",
      "key": "v-1885256e",
      "path": "/think/%E5%A5%A5%E6%96%AF%E6%9C%AC%E6%A3%80%E6%A0%B8%E8%A1%A8%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "一、能否他用",
          "slug": "一、能否他用"
        },
        {
          "level": 3,
          "title": "二、能否借用",
          "slug": "二、能否借用"
        },
        {
          "level": 3,
          "title": "三、能否改变",
          "slug": "三、能否改变"
        },
        {
          "level": 3,
          "title": "四、能否扩大",
          "slug": "四、能否扩大"
        },
        {
          "level": 3,
          "title": "八、能否颠倒",
          "slug": "八、能否颠倒"
        },
        {
          "level": 3,
          "title": "九、能否组合",
          "slug": "九、能否组合"
        }
      ]
    },
    {
      "title": "树上的男爵",
      "frontmatter": {},
      "regularPath": "/read/%E6%A0%91%E4%B8%8A%E7%9A%84%E7%94%B7%E7%88%B5.html",
      "relativePath": "read/树上的男爵.md",
      "key": "v-474ce003",
      "path": "/read/%E6%A0%91%E4%B8%8A%E7%9A%84%E7%94%B7%E7%88%B5.html"
    },
    {
      "title": "醉汉的脚步",
      "frontmatter": {},
      "regularPath": "/read/%E9%86%89%E6%B1%89%E7%9A%84%E8%84%9A%E6%AD%A5.html",
      "relativePath": "read/醉汉的脚步.md",
      "key": "v-22f72a52",
      "path": "/read/%E9%86%89%E6%B1%89%E7%9A%84%E8%84%9A%E6%AD%A5.html",
      "headers": [
        {
          "level": 3,
          "title": "1、生日问题",
          "slug": "_1、生日问题"
        },
        {
          "level": 3,
          "title": "2、两女儿问题",
          "slug": "_2、两女儿问题"
        },
        {
          "level": 3,
          "title": "3、两女儿问题（进阶一）",
          "slug": "_3、两女儿问题（进阶一）"
        },
        {
          "level": 3,
          "title": "4、三门问题",
          "slug": "_4、三门问题"
        },
        {
          "level": 3,
          "title": "5、两女儿问题（进阶二）",
          "slug": "_5、两女儿问题（进阶二）"
        }
      ]
    },
    {
      "title": "think",
      "frontmatter": {},
      "regularPath": "/think/",
      "relativePath": "think/README.md",
      "key": "v-30d11e4b",
      "path": "/think/"
    },
    {
      "title": "view",
      "frontmatter": {},
      "regularPath": "/view/",
      "relativePath": "view/README.md",
      "key": "v-19f300e1",
      "path": "/view/"
    },
    {
      "title": "JS中的this",
      "frontmatter": {},
      "regularPath": "/code/frontend/JS%E4%B8%AD%E7%9A%84this.html",
      "relativePath": "code/frontend/JS中的this.md",
      "key": "v-01063b1e",
      "path": "/code/frontend/JS%E4%B8%AD%E7%9A%84this.html",
      "headers": [
        {
          "level": 3,
          "title": "一、开始",
          "slug": "一、开始"
        },
        {
          "level": 3,
          "title": "二、四条绑定规则",
          "slug": "二、四条绑定规则"
        },
        {
          "level": 3,
          "title": "三、四条绑定规则的优先级",
          "slug": "三、四条绑定规则的优先级"
        },
        {
          "level": 3,
          "title": "四、箭头函数里的this",
          "slug": "四、箭头函数里的this"
        },
        {
          "level": 3,
          "title": "五、参考阅读",
          "slug": "五、参考阅读"
        }
      ]
    },
    {
      "title": "黑镜（第四季）",
      "frontmatter": {},
      "regularPath": "/view/%E9%BB%91%E9%95%9C%EF%BC%88%E7%AC%AC%E5%9B%9B%E5%AD%A3%EF%BC%89.html",
      "relativePath": "view/黑镜（第四季）.md",
      "key": "v-1238476e",
      "path": "/view/%E9%BB%91%E9%95%9C%EF%BC%88%E7%AC%AC%E5%9B%9B%E5%AD%A3%EF%BC%89.html"
    },
    {
      "title": "Progressive Web App(PWA)",
      "frontmatter": {},
      "regularPath": "/code/frontend/PWA.html",
      "relativePath": "code/frontend/PWA.md",
      "key": "v-4260720a",
      "path": "/code/frontend/PWA.html",
      "headers": [
        {
          "level": 2,
          "title": "一、前期介绍",
          "slug": "一、前期介绍"
        },
        {
          "level": 3,
          "title": "1、简单介绍",
          "slug": "_1、简单介绍"
        },
        {
          "level": 3,
          "title": "2、为什么W3C和谷歌在推广这项技术",
          "slug": "_2、为什么w3c和谷歌在推广这项技术"
        },
        {
          "level": 3,
          "title": "3、PWA的核心目标",
          "slug": "_3、pwa的核心目标"
        },
        {
          "level": 2,
          "title": "二、特点",
          "slug": "二、特点"
        },
        {
          "level": 3,
          "title": "1、PWA的特点",
          "slug": "_1、pwa的特点"
        },
        {
          "level": 3,
          "title": "2、特点详解",
          "slug": "_2、特点详解"
        },
        {
          "level": 2,
          "title": "3、开发者如何了解是否具备这些特点",
          "slug": "_3、开发者如何了解是否具备这些特点"
        },
        {
          "level": 2,
          "title": "三、有哪些企业已经在使用PWA？",
          "slug": "三、有哪些企业已经在使用pwa？"
        },
        {
          "level": 2,
          "title": "四、代码细节",
          "slug": "四、代码细节"
        },
        {
          "level": 3,
          "title": "1、代码可以参考的是谷歌的官方教程",
          "slug": "_1、代码可以参考的是谷歌的官方教程"
        },
        {
          "level": 3,
          "title": "2、缓存策略",
          "slug": "_2、缓存策略"
        },
        {
          "level": 3,
          "title": "3、官方工具",
          "slug": "_3、官方工具"
        },
        {
          "level": 2,
          "title": "五、小结",
          "slug": "五、小结"
        },
        {
          "level": 2,
          "title": "参考文章（部分链接需要带好梯子）",
          "slug": "参考文章（部分链接需要带好梯子）"
        }
      ]
    },
    {
      "title": "jsonp的一般原理",
      "frontmatter": {},
      "regularPath": "/code/frontend/jsonp%E7%9A%84%E4%B8%80%E8%88%AC%E5%8E%9F%E7%90%86.html",
      "relativePath": "code/frontend/jsonp的一般原理.md",
      "key": "v-7a1161be",
      "path": "/code/frontend/jsonp%E7%9A%84%E4%B8%80%E8%88%AC%E5%8E%9F%E7%90%86.html"
    },
    {
      "title": "人情、面子与权利的再生产",
      "frontmatter": {},
      "regularPath": "/read/%E4%BA%BA%E6%83%85%E3%80%81%E9%9D%A2%E5%AD%90%E4%B8%8E%E6%9D%83%E5%88%A9%E7%9A%84%E5%86%8D%E7%94%9F%E4%BA%A7.html",
      "relativePath": "read/人情、面子与权利的再生产.md",
      "key": "v-16a3280e",
      "path": "/read/%E4%BA%BA%E6%83%85%E3%80%81%E9%9D%A2%E5%AD%90%E4%B8%8E%E6%9D%83%E5%88%A9%E7%9A%84%E5%86%8D%E7%94%9F%E4%BA%A7.html",
      "headers": [
        {
          "level": 3,
          "title": "《人情、面子与权利的再生产》之中国人际关系模式",
          "slug": "《人情、面子与权利的再生产》之中国人际关系模式"
        },
        {
          "level": 3,
          "title": "《人情、面子与权利的再生产》之脸和面子的同质性以及异质性",
          "slug": "《人情、面子与权利的再生产》之脸和面子的同质性以及异质性"
        },
        {
          "level": 3,
          "title": "《人情、面子与权利的再生产》之情理社会中的社会交换方式",
          "slug": "《人情、面子与权利的再生产》之情理社会中的社会交换方式"
        }
      ]
    },
    {
      "title": "大而不倒",
      "frontmatter": {},
      "regularPath": "/read/%E5%A4%A7%E8%80%8C%E4%B8%8D%E5%80%92.html",
      "relativePath": "read/大而不倒.md",
      "key": "v-7f0cad55",
      "path": "/read/%E5%A4%A7%E8%80%8C%E4%B8%8D%E5%80%92.html",
      "headers": [
        {
          "level": 3,
          "title": "一、主要标志性事件",
          "slug": "一、主要标志性事件"
        },
        {
          "level": 3,
          "title": "二、危机发生的原因",
          "slug": "二、危机发生的原因"
        },
        {
          "level": 3,
          "title": "三、政府在经融危机所面临的困境",
          "slug": "三、政府在经融危机所面临的困境"
        },
        {
          "level": 3,
          "title": "四、关于雷曼的悲情角色",
          "slug": "四、关于雷曼的悲情角色"
        },
        {
          "level": 3,
          "title": "五、关于《大而不倒》、《监守自盗》这两部纪录片",
          "slug": "五、关于《大而不倒》、《监守自盗》这两部纪录片"
        },
        {
          "level": 3,
          "title": "六、关于大企业的大而不倒",
          "slug": "六、关于大企业的大而不倒"
        },
        {
          "level": 3,
          "title": "七、关于财政部长保尔森的功过是非",
          "slug": "七、关于财政部长保尔森的功过是非"
        }
      ],
      "lastUpdated": "2020/02/12"
    },
    {
      "title": "理解国际冲突",
      "frontmatter": {},
      "regularPath": "/read/%E7%90%86%E8%A7%A3%E5%9B%BD%E9%99%85%E5%86%B2%E7%AA%81.html",
      "relativePath": "read/理解国际冲突.md",
      "key": "v-c591bb52",
      "path": "/read/%E7%90%86%E8%A7%A3%E5%9B%BD%E9%99%85%E5%86%B2%E7%AA%81.html"
    },
    {
      "title": "信息过剩与极简主义",
      "frontmatter": {},
      "regularPath": "/think/%E4%BF%A1%E6%81%AF%E8%BF%87%E5%89%A9%E4%B8%8E%E6%9E%81%E7%AE%80%E4%B8%BB%E4%B9%89.html",
      "relativePath": "think/信息过剩与极简主义.md",
      "key": "v-7b2e433d",
      "path": "/think/%E4%BF%A1%E6%81%AF%E8%BF%87%E5%89%A9%E4%B8%8E%E6%9E%81%E7%AE%80%E4%B8%BB%E4%B9%89.html"
    },
    {
      "title": "Typescript小结",
      "frontmatter": {},
      "regularPath": "/code/frontend/Typescript%E5%B0%8F%E7%BB%93.html",
      "relativePath": "code/frontend/Typescript小结.md",
      "key": "v-19b77116",
      "path": "/code/frontend/Typescript%E5%B0%8F%E7%BB%93.html",
      "headers": [
        {
          "level": 3,
          "title": "一、什么是 TypeScript",
          "slug": "一、什么是-typescript"
        },
        {
          "level": 3,
          "title": "二、TypeScript 的特点",
          "slug": "二、typescript-的特点"
        },
        {
          "level": 3,
          "title": "三、安装 TypeScript",
          "slug": "三、安装-typescript"
        },
        {
          "level": 3,
          "title": "四、推荐编辑器",
          "slug": "四、推荐编辑器"
        },
        {
          "level": 3,
          "title": "五、一个简单的例子",
          "slug": "五、一个简单的例子"
        },
        {
          "level": 3,
          "title": "六、空值",
          "slug": "六、空值"
        },
        {
          "level": 3,
          "title": "七、Null 和 Undefined",
          "slug": "七、null-和-undefined"
        },
        {
          "level": 3,
          "title": "八、任意值",
          "slug": "八、任意值"
        },
        {
          "level": 3,
          "title": "九、类型推论",
          "slug": "九、类型推论"
        },
        {
          "level": 3,
          "title": "十、联合类型",
          "slug": "十、联合类型"
        },
        {
          "level": 3,
          "title": "十一、接口",
          "slug": "十一、接口"
        },
        {
          "level": 3,
          "title": "十二、定义数组类型",
          "slug": "十二、定义数组类型"
        },
        {
          "level": 3,
          "title": "十三、约束函数的类型",
          "slug": "十三、约束函数的类型"
        },
        {
          "level": 3,
          "title": "十四、申明文件",
          "slug": "十四、申明文件"
        },
        {
          "level": 3,
          "title": "十五、内置对象",
          "slug": "十五、内置对象"
        },
        {
          "level": 3,
          "title": "十六、类型别名",
          "slug": "十六、类型别名"
        },
        {
          "level": 3,
          "title": "十七、字符串字面量类型",
          "slug": "十七、字符串字面量类型"
        },
        {
          "level": 3,
          "title": "十八、类",
          "slug": "十八、类"
        },
        {
          "level": 3,
          "title": "十九、类与接口",
          "slug": "十九、类与接口"
        },
        {
          "level": 3,
          "title": "二十、混合类型",
          "slug": "二十、混合类型"
        },
        {
          "level": 3,
          "title": "二十一、泛型",
          "slug": "二十一、泛型"
        }
      ]
    },
    {
      "title": "python基础语法",
      "frontmatter": {},
      "regularPath": "/code/python/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
      "relativePath": "code/python/基础语法.md",
      "key": "v-1175e57a",
      "path": "/code/python/%E5%9F%BA%E7%A1%80%E8%AF%AD%E6%B3%95.html",
      "headers": [
        {
          "level": 3,
          "title": "一、数据类型和变量",
          "slug": "一、数据类型和变量"
        },
        {
          "level": 3,
          "title": "二、使用list",
          "slug": "二、使用list"
        },
        {
          "level": 3,
          "title": "三、使用tuple",
          "slug": "三、使用tuple"
        },
        {
          "level": 3,
          "title": "四、循环",
          "slug": "四、循环"
        },
        {
          "level": 3,
          "title": "五、使用dict",
          "slug": "五、使用dict"
        },
        {
          "level": 3,
          "title": "六、使用set",
          "slug": "六、使用set"
        },
        {
          "level": 3,
          "title": "七、函数",
          "slug": "七、函数"
        },
        {
          "level": 3,
          "title": "八、切片",
          "slug": "八、切片"
        },
        {
          "level": 3,
          "title": "九、迭代",
          "slug": "九、迭代"
        },
        {
          "level": 3,
          "title": "十、列表生成式",
          "slug": "十、列表生成式"
        },
        {
          "level": 3,
          "title": "十一、生成器",
          "slug": "十一、生成器"
        },
        {
          "level": 3,
          "title": "十二、迭代器",
          "slug": "十二、迭代器"
        },
        {
          "level": 3,
          "title": "十三、高阶函数",
          "slug": "十三、高阶函数"
        },
        {
          "level": 3,
          "title": "十四、返回函数",
          "slug": "十四、返回函数"
        },
        {
          "level": 3,
          "title": "十五、匿名函数",
          "slug": "十五、匿名函数"
        },
        {
          "level": 3,
          "title": "十六、装饰器",
          "slug": "十六、装饰器"
        },
        {
          "level": 3,
          "title": "十七、偏函数",
          "slug": "十七、偏函数"
        },
        {
          "level": 3,
          "title": "十八、类和实例",
          "slug": "十八、类和实例"
        },
        {
          "level": 3,
          "title": "十九、__init__方法",
          "slug": "十九、-init-方法"
        },
        {
          "level": 3,
          "title": "二十、私有变量",
          "slug": "二十、私有变量"
        },
        {
          "level": 3,
          "title": "二十一、继承",
          "slug": "二十一、继承"
        },
        {
          "level": 3,
          "title": "二十二、MixIn",
          "slug": "二十二、mixin"
        },
        {
          "level": 3,
          "title": "二十三、判断对象类型",
          "slug": "二十三、判断对象类型"
        },
        {
          "level": 3,
          "title": "二十四、使用dir()",
          "slug": "二十四、使用dir"
        },
        {
          "level": 3,
          "title": "二十五、实例属性和类属性",
          "slug": "二十五、实例属性和类属性"
        },
        {
          "level": 3,
          "title": "二十六、使用__slots__",
          "slug": "二十六、使用-slots"
        },
        {
          "level": 3,
          "title": "二十七、使用@property",
          "slug": "二十七、使用-property"
        }
      ]
    }
  ],
  "themeConfig": {
    "sidebarDepth": 0,
    "lastUpdated": "上次更新",
    "displayAllHeaders": true,
    "repo": "https://github.com/WangYuLue/docs",
    "docsDir": "docs",
    "editLinks": true,
    "editLinkText": "在 GitHub 上编辑此页",
    "nav": [
      {
        "text": "Code",
        "link": "/code/"
      },
      {
        "text": "Read",
        "link": "/read/"
      },
      {
        "text": "View",
        "link": "/view/"
      },
      {
        "text": "Think",
        "link": "/think/"
      }
    ],
    "sidebar": {
      "/code/": [
        {
          "title": "前端",
          "children": [
            "frontend/PWA",
            "frontend/304状态码",
            "frontend/pushState与replaceState",
            "frontend/原型链",
            "frontend/JS中的this",
            "frontend/JS获得浏览器的各种高度与宽度",
            "frontend/JS中监听对象中变量的变化",
            "frontend/CSS踩坑小结",
            "frontend/ES6中类的使用简明教程",
            "frontend/JS检测网络带宽",
            "frontend/JS查询URL字符串中的参数",
            "frontend/JS中apply、call、bind的用法",
            "frontend/Object.defineProperty",
            "frontend/Object.create",
            "frontend/JS中slice、substring、substr的区别",
            "frontend/Sass小结"
          ]
        },
        {
          "title": "git",
          "children": [
            "git/常见用法",
            "git/submodule"
          ]
        },
        {
          "title": "nginx",
          "children": [
            "nginx/重写路径",
            "nginx/通用配置优化"
          ]
        },
        {
          "title": "python",
          "children": [
            "python/基础语法"
          ]
        },
        {
          "title": "快捷键",
          "children": [
            {
              "title": "Chrome",
              "path": "hot-key/Chrome"
            },
            {
              "title": "Mac",
              "path": "hot-key/Mac"
            },
            {
              "title": "Vimium",
              "path": "hot-key/Vimium"
            },
            {
              "title": "VSCode",
              "path": "hot-key/VSCode"
            }
          ]
        }
      ],
      "/read/": [
        "奥斯本检核表法",
        "大而不倒",
        "大教堂和集市",
        "动物农场",
        "寒冬夜行人",
        "理解国际冲突",
        "穷爸爸富爸爸",
        "人情、面子与权利的再生产",
        "树上的男爵",
        "醉汉的脚步"
      ],
      "/view/": [
        "黑镜（第四季）"
      ],
      "/think/": [
        "信息过剩与极简主义"
      ]
    }
  }
}